name: Gerar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Extrair projeto
        run: |
          mkdir projeto
          unzip -q MusicaChallengeBR_RealAudio.zip -d projeto

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Gerar APK
        working-directory: projeto
        run: gradle assembleDebug --no-daemon

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: MusicaChallenge-APK
          path: projeto/app/build/outputs/apk/debug/app-debug.apk
